### ISSUE TITLE
Warriors - Silence spell

### ISSUE THREAD

**Issue by vainzki** [scotty0100/wowascension-issues#112] opened 2013-09-09 19:07 UTC
Account Name (for vote points rewards): Vainzki
Map & Area: Everywhere
How to replicate the bug: Make a warrior, get someone to silence you or walk to a mob that silences.
What happens: Silence casted on you will prevent the use of Shield Slam, Revenge and Sunder Armor among other abilities. You get an error message stating that You are mounted.
What should happen: These abilities should not be affected by silence. Only shouts like Taunt or Demoralizing Shout should be affected
Located on WoWHead Map (if applicable):
Source (proof, if applicable): 

Extra Information:

**Comment by kamicolo** [comment] 2014-10-18 22:26
Works as intended now closing this issue

**Closed as completed by kamicolo** 2014-10-18 22:26 UTC
Labels: NPC, Approved, Fixed / Closed
