### ISSUE TITLE
Rockbiter

### ISSUE THREAD

**Issue by CravenEsq** [scotty0100/wowascension-issues#57] opened 2013-08-19 19:05 UTC
Reported by barrotes:

"hi rockbitter isnt giving extra ap instead procs flametongue which is really bad for leveling ty this is a shammy bug ty"

**Comment by scotty0100** [comment] 2014-09-21 19:28
Rockbiter has been fixed now for a while. Tested all 7 ranks today and was working as intended but was fixed 4-5 months ago

**Closed as completed by scotty0100** 2014-09-21 19:28 UTC
Labels: Approved, Fixed / Closed, Skill / Spell / Ability, Shaman
