### ISSUE TITLE
Pet Issues on Hunters 

### ISSUE THREAD

**Issue by Skylark14** [scotty0100/wowascension-issues#234] opened 2014-02-10 16:39 UTC
Name: Breena
Account Name (for vote points rewards): Skylark
Map & Area: general

Stay Command: Does not make the pet stay, only makes them run off
Passive Command: If you are in combat this does nothing, you do not get any error message saying you can't do that yet either.
Dash Command: If you have Dash off your pet should run to attack at normal speed, it does not do this only 'walks' fast.
Similar thing happens with Dash on but on CD.

Extra Information:

**Comment by Nelway** [comment] 2014-02-11 14:42
I haven't experimented with dash yet but I can confirm the first 2 issues.

This is merely a guess but the stay command bug might be just a visual glitch as the pet seems to return at incredible speeds, sometimes even teleporting right back if you issue a follow or attack order. This would be easy to test by commanding the pet to stay and watch it bug-run into some mobs. If it doesn't aggro them, then it's just a visual glitch.

I'd also like to add 2 more bugs:
- The pet attack command seems to be based on the pet's line of sight.

If the pet doesn't have the target in its LoS, it won't attack. The pet should be able to attack anything that the hunter can target and has a valid path to, irrespective of LoS.
- Takk the Leaper (rare lvl 19 raptor in the Barrens) has a bugged damage output - it deals about 20-30 dps more than other pets of the same level (the difference increases throughout the levels). There seemed to be a similar bug on Feenix's Emerald Dream (it was fixed eventually). I haven't tested other raptors but the WC ones may be affected as well, based on Feenix bug reports.

**Comment by Swater96** [comment] 2014-02-12 05:02
Pet Stay Fix: https://github.com/Swater96/mangos-classic/commit/333e3a56dd2a211cd13b8328b7db2eaccc801e8d

**Comment by Skylark14** [comment] 2014-02-12 07:58
Exactly the same happens with lock pets, tested in IF and void ran off and fell down into the lava, only came back when I clicked follow, I Faced another way and it did the same and got stuck by the wall.

**Comment by Swater96** [comment] 2014-02-12 13:43
The fix I found will make pets stay correctly if you are standing still. If you are running or jumping it will still run away when you click stay. Weird issue. I'll probably have to talk to the core team.

**Comment by kamicolo** [comment] 2014-10-19 16:06
Closing https://github.com/scotty0100/wowascension-issues/issues/232

**Closed as completed by kamicolo** 2014-10-19 16:06 UTC
Labels: Duplicate, Approved, Skill / Spell / Ability, Hunter
