### ISSUE TITLE
Gameobject - Gnomish Battle Chicken

### ISSUE THREAD

**Issue by Raewhen** [scotty0100/wowascension-issues#120] opened 2013-09-13 17:02 UTC
The trinket equips and clicks properly. It goes on Cooldown and the animation displays. But nothing else happens. No chicken. No anything.

**Comment by Raewhen** [comment] 2013-09-13 19:25
Goblin Bomb Dispenser Is Similarly broken. Equpis, clicks, and goes on cooldown properly. But nothing summoned.

**Comment by Skylark14** [comment] 2013-09-22 23:28
This seems to be affecting all trinkets

Also quest for selecting gnomeish or goblin speciality doesn't seem to be active which could probably be the cause of this issue as these trinket's can only be used for one or the other specialities.

**Comment by Raewhen** [comment] 2013-09-23 19:19
There is a difference between the activities between some of the trinkets.
The gnomish battle chicken and goblin bomb dispenser i can equip and click
on them. I get animations on my character but the chicken and bomb
respectively do not spawn. The Ultra Safe Transporter: Gnomerigan, however,
I can not even equip. The game sites that i lack gnomish engineering.

**Comment by kamicolo** [comment] 2014-10-19 19:18
closing: https://github.com/scotty0100/wowascension-issues/issues/167

**Closed as completed by kamicolo** 2014-10-19 19:18 UTC
Labels: Duplicate, Approved, Game Objects
