### ISSUE TITLE
Mobs aggro through walls

### ISSUE THREAD

**Issue by CravenEsq** [scotty0100/wowascension-issues#41] opened 2013-08-19 18:56 UTC
Reported by Scarlet:

"Name: Scarlet
Area: Elwynn Forest, Fargodeep Mine
How to replicate the bug: run around the mine and inside it
What happens: monsters aggro through walls and hills (i.e. when you are inside the mine, spiders from above could aggro you). Then they go through walls and attack.
What should happen: mobs should respect line of sight, and not aggro through walls and such."

**Comment by scotty0100** [comment] 2014-10-06 18:09
Closing, duplicate of https://github.com/scotty0100/wowascension-issues/issues/423

Keeping all of these issues into one

**Closed as completed by scotty0100** 2014-10-06 18:09 UTC
Labels: Duplicate, NPC, Approved
