### ISSUE TITLE
BRD Arena Event Not Starting

### ISSUE THREAD

**Issue by GiftedAscension** [scotty0100/wowascension-issues#278] opened 2014-04-21 16:17 UTC
Went in with a group of all 60s, entered the arena, stood on the grate and High Justice Grimstone appears, but he just paces back and forth and doesn't start the arena. Gates go down and I'm stuck. Had to portal out..

This is the second time this has happened to me in a row.

~Gifted

**Comment by Skylark14** [comment] 2014-04-22 09:55
Its possible it could be due to the dbase not loading properly.  Server restart today hopefully will fix this issue.  Please let me know if it does fix it.

**Comment by Faraday1** [comment] 2014-04-24 10:14
Confirmed, this is now working. Closing, thanks for reporting it!

**Closed as completed by Faraday1** 2014-04-24 10:14 UTC
Labels: NPC, Fixed / Closed
