### ISSUE TITLE
Warlock Pets 

### ISSUE THREAD

**Issue by Krysa** [scotty0100/wowascension-issues#223] opened 2014-01-27 02:43 UTC
Name: Krysa
Account Name (for vote points rewards): Isole
Map & Area: Dun Morough and Elwynn
How to replicate the bug: Summon imp, train imp (optional, but part of issue), dismiss imp (or hearth, logout, die, etc).  Imp disappears.  Summon imp again.
What happens: When the new imp is summoned, it is a new imp with a new name.  Any skills that were trained are lost and must be retrained at cost.
What should happen: The warlock should have the same imp with the same name and skills.  All skills should be retained every time the imp is summoned.

Extra Information:  I'm not sure if this pertains to other warlock pets yet as I've only been able to test on the imp.  Also the imp should remain summoned at logout or hearthing, but the main issue is summoning a new imp and having to retrain.

**Comment by Skylark14** [comment] 2014-01-27 04:44
Tested and confirmed yesterday.  Reported to Honch.

**Comment by Skylark14** [comment] 2014-01-27 12:53
Hopefully should be fixed, tested and appeared to be working now ok.  Will leave this open for a few days, any problems please update here. Thankyou

**Comment by scotty0100** [comment] 2014-02-02 19:52
Closed.

**Comment by Skylark14** [comment] 2014-02-05 19:47
RE-opened - Krysa's pets were different when resummoned today (5/2/14) after being logged out for two days - had also lost their spells.

**Comment by Skylark14** [comment] 2014-02-06 19:28
Noh's imp renamed on logout and lost spells.  Not been on for a few days.  Notified me today 6/2/14

**Comment by Skylark14** [comment] 2014-03-19 06:03
Krysa's pets were different when resummoned today (19/3/14).  She had logged in around 11am 18th and they were fine, logged in again around 3am 19th and they were different and had lost their spells.

**Comment by Skylark14** [comment] 2014-03-19 11:11
14th March: Toots also lost her pets, new summoned ones had no spells.

Also Demondots lost her pets - date unknown as had not been on for a while.

**Comment by Skylark14** [comment] 2014-03-29 09:04
28/3/14 - Toots lost her pets.  New summoned ones had no spells. (was there 27/3/14 but disappeared sometime overnight)

**Comment by Skylark14** [comment] 2014-03-29 09:05
28/3/14 -  Krysa losts her pets again today, sometime between 2pm and 11:30pm server time.

**Comment by Skylark14** [comment] 2014-08-19 06:04
Seems to be fixed now

**Closed as completed by Skylark14** 2014-08-19 06:04 UTC
Labels: Approved, Fixed / Closed, Skill / Spell / Ability, Warlock
